import { defineAd } from './types';

export const adSpec = defineAd({
  id: 'nova-audio-launch',
  name: 'Nova Audio launch ad',
  theme: {
    background: '#0a0f1e',
    surface: '#111a31',
    text: '#f8fafc',
    mutedText: '#b8c4dc',
    accent: '#7c3aed',
    accentText: '#ffffff',
    border: '#263659',
  },
  elements: [
    {
      id: 'headline',
      type: 'text',
      role: 'primary',
      priority: 1,
      label: 'Headline',
      text: 'Studio sound. Zero wires.',
      allowHide: false,
      allowTruncate: true,
      sizing: {
        minFontSize: 22,
        preferredFontSize: 42,
        maxFontSize: 66,
        preferredLines: 2,
        minLines: 1,
        lineHeight: 1.04,
      },
      weight: 800,
    },
    {
      id: 'product-image',
      type: 'image',
      role: 'hero',
      priority: 1,
      label: 'Product image',
      src: '/nova-headphones.svg',
      alt: 'Nova Arc wireless headphones',
      objectFit: 'contain',
      allowHide: false,
      sizing: {
        minHeight: 90,
        preferredHeight: 250,
        maxHeight: 620,
      },
    },
    {
      id: 'price',
      type: 'text',
      role: 'secondary',
      priority: 2,
      label: 'Price',
      text: '₹4,999',
      allowHide: false,
      allowTruncate: false,
      sizing: {
        minFontSize: 18,
        preferredFontSize: 28,
        maxFontSize: 44,
        preferredLines: 1,
        minLines: 1,
        lineHeight: 1.1,
      },
      weight: 700,
    },
    {
      id: 'cta',
      type: 'button',
      role: 'action',
      priority: 2,
      label: 'Call to action',
      text: 'Shop now',
      allowHide: false,
      sizing: {
        minHeight: 40,
        preferredHeight: 54,
        maxHeight: 72,
        minFontSize: 14,
        preferredFontSize: 18,
        maxFontSize: 26,
      },
    },
    {
      id: 'supporting-copy',
      type: 'text',
      role: 'supporting',
      priority: 3,
      label: 'Supporting copy',
      text: 'Adaptive ANC • 48-hour battery • Hi-Res Audio',
      allowHide: true,
      allowTruncate: true,
      sizing: {
        minFontSize: 13,
        preferredFontSize: 18,
        maxFontSize: 28,
        preferredLines: 2,
        minLines: 1,
        lineHeight: 1.25,
      },
      weight: 500,
    },
    {
      id: 'logo',
      type: 'image',
      role: 'branding',
      priority: 4,
      label: 'Branding',
      src: '/nova-logo.svg',
      alt: 'Nova Audio',
      objectFit: 'contain',
      allowHide: true,
      sizing: {
        minHeight: 24,
        preferredHeight: 38,
        maxHeight: 52,
      },
    },
  ] as const,
});
